SRC += muse.c
LAYOUTS_HAS_RGB = yes

TAP_DANCE_ENABLE=yes
LINK_TIME_OPTIMIZATION_ENABLE =yes
Space_Cadet = no
POINTING_DEVICE_ENABLE = no
EXTRAFLAGS += -flto
RGBLIGHT_ANIMATIONS=yes
RGBLED_NUM = 99
RGBLIGHT_ENABLE = yes
