OLED_DRIVER_ENABLE = no   # Enables the use of OLED displays
ENCODER_ENABLE = no       # ENables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
TAP_DANCE_ENABLE = yes
MIDI_ENABLE = no            # MIDI support (+2400 to 4200, depending on config)
UNICODE_ENABLE = no         # Unicode
BLUETOOTH_ENABLE = no       # Enable Bluetooth with the Adafruit EZ-Key HID
AUDIO_ENABLE = no           # Audio output on port C6
FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
HD44780_ENABLE = no 		# Enable support for HD44780 based LCDs (+400)
COMBO_ENABLE = no 
CONSOLE_ENABLE = no 
TERMINAL_ENABLE = no 
KEY_LOCK_ENABLE = no 
NKRO_ENABLE = no
SPACE_CADET_ENABLE = no
MOUSEKEYS_ENABLE = no
EXTRAFLAGS += -flto
